captcha_timeout: 300
element_wait_time: 30
max_pages: 100
proxies: []
request_delay: 1.5
thread_workers: 5
user_agents:
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
  Chrome/91.0.4472.124 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like
  Gecko) Version/14.1.1 Safari/605.1.15
website: https://www.jegs.com/v/ACC-Performance/082?Tab=GROUP
